openapi: '3.0.3'
info:
  title: ECOMMERCE
  version: '1.0'
servers:
  - url: http://localhost:4000/api/v1
    description: v1 - localhost
  - url: https://ecommerce-backend-lxhy.onrender.com/api/v1
    description: v1 - live
security:
  - BearerAuth: []
      


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  