openapi: '3.0.3'
info:
  title: ECOMMERCE
  version: '1.0'
servers:
  - url: http://localhost:4000/api/v1
    description: v1 - localhost
  - url: https://ecommerce-backend-lxhy.onrender.com/api/v1
    description: v1 - live

paths:
  /product/create:
    $ref: '../app/v1/product/docs.yaml#/paths/~1product~1create'
